# Generated by Django 4.2.7 on 2025-08-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunidadvoluntariado',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Oportunidad de Voluntariado', 'verbose_name_plural': 'Oportunidades de Voluntariado'},
        ),
        migrations.AddField(
            model_name='oportunidadvoluntariado',
            name='beneficios',
            field=models.TextField(blank=True, default='', help_text='Describe los beneficios que ofrece el voluntariado'),
        ),
        migrations.AddField(
            model_name='oportunidadvoluntariado',
            name='horario',
            field=models.CharField(blank=True, default='', help_text='Ej: Lunes a Viernes, 9:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='oportunidadvoluntariado',
            name='requisitos',
            field=models.TextField(blank=True, default='', help_text='Lista los requisitos necesarios para el voluntariado'),
        ),
    ]
