# Generated by Django 4.2.7 on 2025-08-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteParticipacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField()),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='reportes/evidencias/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oportunidades.oportunidadvoluntariado', verbose_name='oportunidad')),
            ],
            options={
                'verbose_name': 'reporte de participación',
                'verbose_name_plural': 'reportes de participación',
            },
        ),
    ]
