# Generated by Django 4.2.7 on 2025-08-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermutacionParticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_participantes', models.PositiveIntegerField()),
                ('resultado_permutacion', models.BigIntegerField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oportunidades.oportunidadvoluntariado')),
            ],
        ),
    ]
