# Generated by Django 4.2.7 on 2025-08-11 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0002_alter_oportunidadvoluntariado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permutaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPermutacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('oportunidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_entrantes', to='oportunidades.oportunidadvoluntariado')),
                ('oportunidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_salientes', to='oportunidades.oportunidadvoluntariado')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de permutación',
                'verbose_name_plural': 'solicitudes de permutación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='PermutacionParticipantes',
        ),
    ]
