# Generated by Django 4.2.23 on 2025-08-11 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0002_alter_oportunidadvoluntariado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permutaciones', '0002_solicitudpermutacion_delete_permutacionparticipantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermutacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='solicitudpermutacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudpermutacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='solicitudpermutacion',
            name='mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='solicitudpermutacion',
            name='oportunidad_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_entrantes', to='oportunidades.oportunidadvoluntariado', verbose_name='Oportunidad de destino'),
        ),
        migrations.AlterField(
            model_name='solicitudpermutacion',
            name='oportunidad_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_salientes', to='oportunidades.oportunidadvoluntariado', verbose_name='Oportunidad de origen'),
        ),
        migrations.AlterField(
            model_name='solicitudpermutacion',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Receptor'),
        ),
        migrations.AlterField(
            model_name='solicitudpermutacion',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddConstraint(
            model_name='solicitudpermutacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('solicitante', 'receptor', 'oportunidad_origen', 'oportunidad_destino', 'estado'), name='solicitud_permutacion_unica'),
        ),
    ]
