# Generated by Django 4.2.23 on 2025-08-19 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permutaciones', '0003_solicitudpermutacion_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPermutacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación de Solicitud'), ('aceptacion', 'Aceptación de Intercambio'), ('rechazo', 'Rechazo de Solicitud'), ('cancelacion', 'Cancelación de Solicitud')], max_length=20, verbose_name='Tipo de Acción')),
                ('detalles', models.TextField(help_text='Información detallada sobre el cambio realizado', verbose_name='Detalles del Cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='permutaciones.solicitudpermutacion', verbose_name='Solicitud de Permutación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la acción')),
            ],
            options={
                'verbose_name': 'Historial de Permutación',
                'verbose_name_plural': 'Historial de Permutaciones',
                'ordering': ['-fecha'],
                'permissions': [('view_historial_permutacion', 'Puede ver el historial de permutaciones')],
            },
        ),
    ]
