# Generated by Django 4.2.7 on 2025-08-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oportunidades.oportunidadvoluntariado', verbose_name='oportunidad')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
            },
        ),
    ]
