# Generated by Django 4.2.23 on 2025-08-19 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0002_alter_oportunidadvoluntariado_options_and_more'),
        ('inscripciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='oportunidades.oportunidadvoluntariado', verbose_name='oportunidad'),
        ),
    ]
